server:
  port: 8081
management:
  server:
    servlet:
      context-path: "/actuator"
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/management"
  endpoint:
    shutdown:
      enabled: false
info:
  app:
    name: "wordladder"