server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/dbrr
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
management:
  server:
    servlet:
      context-path: "/actuator"
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/management"
  endpoint:
    shutdown:
      enabled: false
info:
  app:
    name: "wordladder"