version: '3'
services:
  login:
    container_name: login
    image: login
    ports:
      - "8088:8080"
  wordladder:
    container_name: wordladder
    image: wordladder
    ports:
      - "8089:8081"
  mysql:
    container_name: v-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: dbrr
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"